apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-deploy
spec:
  destination:
    name: ''
    namespace: sysdig-agent
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - name: sysdig-clustershield
    kind: Secret
    jsonPointers:
    - /data/sysdig-cluster-nats-password
  - name: sysdig-clustershield-tls-certs
    kind: Secret
    jsonPointers:
    - /data
  - name: sysdig-deploy-clustershield-audit
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
  sources:
  - repoURL: 'https://charts.sysdig.com'
    chart: shield
    targetRevision: 1.6.1
    helm:
      valueFiles:
      - $values/common/shield.yaml
      - $values/prod/sysdig-deploy-lab2.yaml
  - repoURL: 'https://github.com/yoshiouchi/argocd-sysdig-example.git'
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    automated: 
      prune: true
      #selfHeal: true
    syncOptions:
      - CreateNamespace=true
