apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
spec:
  destination:
    namespace: hello-world
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    chart: hello-world
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
